#ifdef __INC_cstdio_
	#include <stdio.h>
#endif

#ifdef __INC_yaml_h
	#include <yaml.h>
#endif

#ifdef __INC_assert_h
	#include <assert.h>
#endif

#ifdef __INC_stddef
	#include <stddef.h>
#endif

#ifdef __INC_yaml_private
	#include <yaml_private.h>
#endif

#ifdef __INC_yaml_config
	#include <yaml_config.h>
#endif

#ifdef __INC_string
	#include <string.h>
#endif

#ifdef __INC_stdlib
	#include <stdlib.h>
#endif

#ifdef __INC_stdbool
	#include <stdbool.h>
#endif

#ifdef __INC_pthread
	#include <pthread.h>
#endif

#ifdef __INC_netinet
	#include <arpa/inet.h>
	#include <netinet/in.h>
#endif

#ifdef __INC_select
	#include <sys/select.h>
#endif
