#ifdef __INC_stddef
	#include <stddef.h>
#endif

#ifdef __INC_threads
	#include <threads.h>
#endif

#ifdef __INC_time
	#include <time.h>
#endif

#ifdef __INC_sys_types
	#include <sys/types.h>
#endif

#ifdef __INC_stdarg
	#include <stdarg.h>
#endif

#ifdef __INC_stdint
	#include <stdint.h>
#endif

#ifdef __INC_cstdio_
	#define __INC_stdio
#endif

#ifdef __INC_errno
	#include <errno.h>
#endif

#ifdef __INC_unistd
	#include <unistd.h>
#endif

#ifdef __INC_stdio
	#include <stdio.h>
#endif

#ifdef __INC_assert_h
	#include <assert.h>
#endif

#ifdef __INC_string
	#include <string.h>
#endif

#ifdef __INC_stdlib
	#include <stdlib.h>
#endif

#ifdef __INC_stdbool
	#include <stdbool.h>
#endif

#ifdef __INC_pthread
	#include <pthread.h>
#endif

#ifdef __INC_select
	#include <sys/select.h>
#endif

#ifdef __INC_netinet
	#include <arpa/inet.h>
	#include <netinet/in.h>
#endif

#ifdef __INC_sys_socket
	#include <sys/socket.h>
#endif

#ifdef __INC_ncurses
	#include <ncurses.h>
#endif
