
#ifdef __INC_stddef
	#include <stddef.h>
#endif

#ifdef __INC_threads
	#include <threads.h>
#endif

#ifdef __INC_time
	#include <time.h>
#endif

#ifdef __INC_sys_types
	#include <sys/types.h>
#endif

#ifdef __INC_stdarg
	#include <stdarg.h>
#endif

#ifdef __INC_stdint
	#include <stdint.h>
#endif

#ifdef __INC_cstdio_
	#define __INC_stdio
#endif

#ifdef __INC_errno
	#include <errno.h>
#endif

#ifdef __INC_unistd
	#include <unistd.h>
#endif

#ifdef __INC_stdio
	#include <stdio.h>
#endif

#ifdef __INC_assert_h
	#include <assert.h>
#endif

#ifdef __INC_string
	#include <string.h>
#endif

#ifdef __INC_stdlib
	#include <stdlib.h>
#endif

#ifdef __INC_stdbool // in some code it made conflict
	#include <stdbool.h>
#endif

#ifdef __INC_pthread
	#include <pthread.h>
#endif

#ifdef __INC_select
	#include <sys/select.h>
#endif

#ifdef __INC_arpa_inet
	#include <arpa/inet.h>
#endif

#ifdef __INC_netinet
	#include <netinet/in.h>
#endif

#ifdef __INC_sys_socket
	#include <sys/socket.h>
#endif

#ifdef __INC_ncurses
	#include <ncurses.h>
#endif

#ifdef __INC_locale
	#include <locale.h>
#endif

#ifdef __INC_strings
	#include <strings.h>
#endif

#ifdef __INC_libgen
	#include <libgen.h>
#endif

#ifdef __INC_sys_time
	#include <sys/time.h>
#endif

#ifdef __INC_fcntl
	#include <fcntl.h>
#endif

#ifdef __INC_netinet_ip
	#include <netinet/ip.h>
#endif

#ifdef __INC_netinet_udp
	#include <netinet/udp.h>
#endif

#ifdef __INC_netinet_tcp
	#include <netinet/tcp.h>
#endif

//#ifdef __INC_linux_tcp
//	#include <linux/tcp.h>
//#endif

#ifdef __INC_limits
	#include <limits.h>
#endif


#ifdef __INC_pcap
	#include <pcap.h>
#endif

#ifdef __INC_signal
	#include <signal.h>
#endif

#ifdef __INC_ctype
	#include <ctype.h>
#endif

#ifdef __INC_semaphore
	#include <semaphore.h>
#endif

#ifdef __INC_stdatomic
	#include <stdatomic.h>
#endif

#ifdef __INC_notcurses
	#include <notcurses/notcurses.h>
#endif

#ifdef __INC_locale
	#include <locale.h>
#endif

#ifdef __INC_net_ethernet
	#include <net/ethernet.h>
#endif

#ifdef __INC_sys_mman
	 #include <sys/mman.h>
#endif

#ifdef __INC_sys_stat
	 #include <sys/stat.h>
#endif

#ifdef __INC_poll
	 #include <poll.h>
#endif

#ifdef __INC_backtrace
	 #include <backtrace.h>
#endif

#ifdef __INC_math
	 #include <math.h>
#endif

#ifdef __INC_err
	 #include <err.h>
#endif

#ifdef _INC_openssl
	#include <openssl/ssl.h>
	#include <openssl/err.h>
#endif

#ifdef __INC_sys_file
	 #include <sys/file.h>
#endif
